# Generated by Django 5.2.6 on 2025-09-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_last_password_reset_requested'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginactivity',
            new_name='accounts_lo_user_id_c06636_idx',
            old_name='accounts_lo_user_id_c7cda0_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivity',
            new_name='accounts_lo_timesta_4b2d4f_idx',
            old_name='accounts_lo_timesta_f21a16_idx',
        ),
    ]
