# Generated by Django 5.2.6 on 2025-09-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_securityactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='identitydocument',
            new_name='accounts_id_documen_bccd95_idx',
            old_name='accounts_id_doc_number_idx',
        ),
        migrations.RenameIndex(
            model_name='securityactivity',
            new_name='accounts_se_user_id_da5bbb_idx',
            old_name='accounts_sec_user_id_6bade9_idx',
        ),
        migrations.RenameIndex(
            model_name='securityactivity',
            new_name='accounts_se_event_t_f71760_idx',
            old_name='accounts_sec_event_t_1e3b22_idx',
        ),
    ]
