# Generated by Django 5.2.6 on 2025-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_accounts_id_doc_number_idx_accounts_id_documen_bccd95_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
