# Generated by Django 5.2.6 on 2025-09-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('kreyol', 'Kreyòl Ayisyen'), ('french', 'Français'), ('english', 'English'), ('spanish', 'Español')], default='kreyol', max_length=20),
        ),
    ]
